---
      
    - name: installing needed packages for redmine.
      apt: name={{ item }} state=present
      with_items: "{{ Needed_Packages }}"
   ##   - libmysqlclient-dev
   ##   - imagemagick   
   ##   - libmagickwand-dev
   ##   - libcurl4-openssl-dev
   ##   - apt-transport-https
  ##   - ca-certificates


    - name: get rvm keys
      command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  
    
    - name: installing curl.
      apt: name=curl state=present

    - name: installing rvm.
      get_url: url=https://get.rvm.io dest=/tmp/rvm.sh 

    - name: install rvm cont.
      command: bash /tmp/rvm.sh stable 

  
    - name: installing ruby.
      command: /usr/local/rvm/bin/rvm install "{{ ver_ruby }}"
       
          
    - name: copy configuration to redmine 
      shell: cp config/configuration.yml.example config/configuration.yml
      args:
        chdir: /usr/share/redmine

    - name: configuraing variables for database
      template: src=database.conf.j2 dest=/etc/redmine/default/database.yml

    - name: installing bundler.
      shell: gem install bundler
      args:
        chdir: /usr/share/redmine
    
    - name: installing bundler cont. 
      shell: bundle install --without development test
      args:
        chdir: /usr/share/redmine


####################

    - name: make needed dirs. 
      shell: mkdir -p tmp tmp/pdf public/plugin_assets
      args:
        chdir: /usr/share/redmine

    - name: chown for dirs.
      shell: sudo chown -R www-data:www-data  log tmp public/plugin_assets Gemfile.lock
      args:
        chdir: /usr/share/redmine


    - name: chmod for dirs. 
      shell: sudo chmod -R 775  log tmp public/plugin_assets
      args:
        chdir: /usr/share/redmine


    - name: chmod for default.
      shell: sudo chmod -R a+r,a+w  /etc/redmine/default
     




######################

    - name: generate secret token. 
      shell: bundle exec rake generate_secret_token
      args:
        chdir: /usr/share/redmine

    - name: rails_env.
      shell: RAILS_ENV=production bundle exec rake db:migrate
      args:
        chdir: /usr/share/redmine


    - name: rails_env cont. 
      shell: RAILS_ENV=production bundle exec rake db:migrate
      args:
        chdir: /usr/share/redmine

###########################################

    - name: installing redmine.
      apt: name=redmine state=present

    - name:   restart nginx
      service: name=nginx state=restarted




 
